Admin/Controllers/lookupsController.cs
 namespace Admin.Controllers
{
	using System;
	using System.Data;
	using System.Linq;
	using Microsoft.AspNetCore.Mvc;
	using Newtonsoft.Json;
	using System.Net.Http;
	using System.Net.Http.Formatting;
	using System.Threading.Tasks;
	using System.Net.Http.Headers;
	using Microsoft.Extensions.Options;
	using Microsoft.AspNetCore.Http;
	using System.Collections.Generic;
	using System.IO;
	using Microsoft.AspNetCore.Hosting;
	using System.Net;
	using FluentValidation.Results;
	using Marketplacenew.Models;
	 //This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:16 
	 
	public class lookupsController : Controller
	{
		private HttpClient  client = new HttpClient();
		private IWebHostEnvironment hostingEnv;
		private IOptions<ApiSettings> _balSettings;
		private string  url = "";
		private string  baseUrl = "";
		public virtual HttpClient getHttpClient()
		{
			client.BaseAddress = new Uri(url);
client.DefaultRequestHeaders.Accept.Clear();
client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("Marketplacenewtoken")); 
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json")); 
return client; 
;
		}
		public lookupsController(IOptions<ApiSettings> ApiSettings, IWebHostEnvironment env)
		{
			this.hostingEnv = env;
_balSettings = ApiSettings;
url = _balSettings.Value.apiURL;
baseUrl = _balSettings.Value.baseURL;
;
		}
		public virtual IActionResult Index()
		{
			return View();
		}
 
		[HttpGet()]
		public virtual async Task<string> get_lookups()
		{
					return await ApiClient.Get_ApiValues(getHttpClient(), "api/lookups/get_lookups");
;
		}
		[HttpGet()]
		public virtual async Task<string> get_lookups_by_entity(string id)
		{
					return await ApiClient.Get_ApiValues(getHttpClient(), "api/lookups/get_lookups_by_entity?id="+id);
;
		}
		public virtual async Task<IActionResult> Create(string id)
		{
					 var jsonObj = await ApiClient.Get_ApiValues(getHttpClient(), "api/lookups/getById_lookups?id="+id);
if(jsonObj.Length > 2)
{
jsonObj = jsonObj.Substring(1, jsonObj.Length - 2);
var model = JsonConvert.DeserializeObject<lookupsModel>(jsonObj);
return View(model);
}
else
return View()
;
		}
		[HttpPost()]
		public virtual async Task<IActionResult> Create(lookupsModel model, IFormCollection collection)
		{
			string message = "";
		 try
		 {
if(HttpContext.Session.GetString("MarketplacenewUserID") != null)
model.createduser =new Guid(HttpContext.Session.GetString("MarketplacenewloginUserID"));
				 if (ModelState.IsValid)
				 {
			  
				 message = await ApiClient.Post_ApiValuesGetString(getHttpClient(),"api/lookups/ins_lookups", model);
			  
				 }
				 else
				 {
						 var errorCollection = string.Join(" | ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
						 message = errorCollection.ToString();
				 }
		 }
		 catch (Exception ex)
		 {
			 message = ex.Message;
		 }
		 ViewData["message"] = message;
			 if(message=="Success"){
TempData["message"] = message;
				 return RedirectToAction("Index");
			 }else{
				  return View(model);
			 }
;
		}
		
		
		 
	 
	}
}

Admin/Controllers/usersController.cs
namespace Admin.Controllers
			{
				using System;
				using System.Data;
				using System.Linq;
				using Microsoft.AspNetCore.Mvc;
				using Newtonsoft.Json;
				using System.Net.Http;
				using System.Net.Http.Formatting;
				using System.Threading.Tasks;
				using System.Net.Http.Headers;
				using Microsoft.Extensions.Options;
				using Microsoft.AspNetCore.Http;
				using System.Collections.Generic;
				using System.IO;
				using Microsoft.AspNetCore.Hosting;
				using System.Net;
				using FluentValidation.Results;
				using Marketplacenew.Models;
				using Microsoft.AspNetCore.Mvc.Infrastructure;
				using Microsoft.AspNetCore.HttpOverrides;
                using Microsoft.Extensions.Configuration;
                using Microsoft.Extensions.Logging;
                using System.Threading;
	            using System.Globalization;
                using System.Text.Json;
using Microsoft.AspNetCore.Authorization;

                
                
                
				//This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:19
				
                
                
                
                
				public class usersController : BaseController
				{	 
					private IWebHostEnvironment hostingEnv;
					private IOptions<ApiSettings> _balSettings;
                    private IOptions<MailSettings> _mailSettings;
					private string  url = "";
					private string  baseUrl = "";
                    private string  adminUrl = "";
                    private string  clientUrl = "";
                    private string  accesskey = "";
					private IHttpContextAccessor _accessor;
                    public IConfiguration Configuration { get; }
                    private readonly ILogger<usersController> _logger;
                    
                    
                    
					public usersController(IConfiguration configuration,IHttpContextAccessor accessor,IOptions<ApiSettings> ApiSettings, IOptions<MailSettings> MailSettings, IWebHostEnvironment env, ILogger<usersController> logger):base( configuration)
					{
                        _logger = logger;
						this.hostingEnv = env;
						_balSettings = ApiSettings;
                        _mailSettings = MailSettings;
						url = _balSettings.Value.apiURL;
						baseUrl = _balSettings.Value.baseURL;
                        adminUrl = _balSettings.Value.adminURL;
                        clientUrl = _balSettings.Value.clientURL;
                        accesskey = _balSettings.Value.accesskey;
 
						_accessor = accessor;
                        Configuration = configuration;
                        
					}
						 
 
                public virtual IActionResult detail()
                {
                    return View();
                }
                     public virtual IActionResult audit()
			         {
					        return View();
			         }
	

					
				
			  public virtual async Task<string> getById_alloweddevices(string usersid)
			  {
					return await ApiClient.Get_ApiValues(getHttpClient(), "api/users/getById_alloweddevices?usersid="+usersid+"&loginUserID="+HttpContext.Session.GetString("MarketplacenewloginUserID"));
					 
			  }


			  public virtual IActionResult CreatePlatform()
			  {
					return View();
			  }	
			  [HttpPost()]
			public virtual async Task<string> CreatePlatform(usersModel model, IFormCollection collection)
			{
				string strReturnMessage = "";
				
				try
				{
					ModelState.Remove("usersid");
					ModelState.Remove("createduser");
                    ModelState.Remove("craftmyapp_actionmethodname");
                    model.craftmyapp_actionmethodname="CreatePlatform";
					
					ModelState.Remove("profilepicture");

					
			 	 
					 if (ModelState.IsValid)
					 {
							 usersModelValidator validator = new usersModelValidator();
							 ValidationResult results = validator.Validate(model);
							 if (!results.IsValid)
							 {
								 var errorCollection = string.Join(" | ", results.Errors.Select(e => e.ErrorMessage.Replace("{propertyName}",e.PropertyName)));
								 strReturnMessage = errorCollection.ToString();
								 foreach (var failure in results.Errors)
								 {
									ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
								 }
							 }
							 else
							 {
								 model.usersid =Guid.NewGuid();
								 var files = Request.Form.Files;
foreach (var file in files) 
{
var filename = ContentDispositionHeaderValue
.Parse(file.ContentDisposition)
.FileName
.Trim('"'); 
string fileExtention = "." + filename.Split('.').Last(); 
Random rnd = new Random();
string uploadFileName = System.Text.RegularExpressions.Regex.Replace(filename.Split('.').First(), @"[^0-9a-zA-Z_.]+", "").Replace(" ", String.Empty)+"_"+"users_" +rnd.Next(1, 10000).ToString() + DateTime.Now.ToString("ddMMyyHHmmss")+ fileExtention;
if (fileExtention != ".")
{
var filanameFolder = hostingEnv.WebRootPath +  "/uploads/"; 
if (!Directory.Exists(filanameFolder))
{
Directory.CreateDirectory(filanameFolder);
}
filename  = filanameFolder + uploadFileName;
using (FileStream fs = System.IO.File.Create(filename))
{
file.CopyTo(fs);
fs.Flush();
}
if (file.Name == "profilepicture")
{
uploadFileName = baseUrl + "/uploads/" + uploadFileName;
model.profilepicture = uploadFileName;
}
}
}

                                 strReturnMessage = await ApiClient.Post_ApiValuesGetString(getHttpClient(),"api/users/Register_Profile", model);
                                    
								 
							 }
					 }
					 else
					 {
							   var errorMessages = ModelState.Where(entry => entry.Value.Errors.Any()).SelectMany(entry => entry.Value.Errors.Select(error => $"{entry.Key}: {error.ErrorMessage}"));
                               var errorCollection = string.Join(" | ", errorMessages);
                               strReturnMessage = errorCollection;
					 }
			 }
			 catch (Exception ex)
			 {
                 
                 _logger.LogError(ex,"An exception occurred in - users / CreatePlatform, Error Message : " + (ex.StackTrace != null ? $", Stack Trace: {ex.StackTrace.ToString()}" :ex.Message));
               
				 strReturnMessage = ex.Message;
			 }
		     ViewData["message"] = strReturnMessage;
			 if(strReturnMessage.Replace("\"", "").Contains("201.1")){
				 TempData["message"] = "Success";
				 
                 
				return "Success";
			 }else{
				  if(strReturnMessage=="401.1")
				  	 	 strReturnMessage = "Authorization Failed";

				  return strReturnMessage;
			 }
 
		   }

			  public virtual IActionResult Register_Profile()
			  {
					return View();
			  }	
			  [HttpPost()]
			public virtual async Task<string> Register_Profile(usersModel model, IFormCollection collection)
			{
				string strReturnMessage = "";
				
				try
				{
					ModelState.Remove("usersid");
					ModelState.Remove("createduser");
                    ModelState.Remove("craftmyapp_actionmethodname");
                    model.craftmyapp_actionmethodname="Register_Profile";
					
					ModelState.Remove("profilepicture");

					
			 	 
					 if (ModelState.IsValid)
					 {
							 usersModelValidator validator = new usersModelValidator();
							 ValidationResult results = validator.Validate(model);
							 if (!results.IsValid)
							 {
								 var errorCollection = string.Join(" | ", results.Errors.Select(e => e.ErrorMessage.Replace("{propertyName}",e.PropertyName)));
								 strReturnMessage = errorCollection.ToString();
								 foreach (var failure in results.Errors)
								 {
									ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
								 }
							 }
							 else
							 {
								 model.usersid =Guid.NewGuid();
								 var files = Request.Form.Files;
foreach (var file in files) 
{
var filename = ContentDispositionHeaderValue
.Parse(file.ContentDisposition)
.FileName
.Trim('"'); 
string fileExtention = "." + filename.Split('.').Last(); 
Random rnd = new Random();
string uploadFileName = System.Text.RegularExpressions.Regex.Replace(filename.Split('.').First(), @"[^0-9a-zA-Z_.]+", "").Replace(" ", String.Empty)+"_"+"users_" +rnd.Next(1, 10000).ToString() + DateTime.Now.ToString("ddMMyyHHmmss")+ fileExtention;
if (fileExtention != ".")
{
var filanameFolder = hostingEnv.WebRootPath +  "/uploads/"; 
if (!Directory.Exists(filanameFolder))
{
Directory.CreateDirectory(filanameFolder);
}
filename  = filanameFolder + uploadFileName;
using (FileStream fs = System.IO.File.Create(filename))
{
file.CopyTo(fs);
fs.Flush();
}
if (file.Name == "profilepicture")
{
uploadFileName = baseUrl + "/uploads/" + uploadFileName;
model.profilepicture = uploadFileName;
}
}
}

                                 strReturnMessage = await ApiClient.Post_ApiValuesGetString(getHttpClient(),"api/users/Register_Profile", model);
                                    
								 
							 }
					 }
					 else
					 {
							   var errorMessages = ModelState.Where(entry => entry.Value.Errors.Any()).SelectMany(entry => entry.Value.Errors.Select(error => $"{entry.Key}: {error.ErrorMessage}"));
                               var errorCollection = string.Join(" | ", errorMessages);
                               strReturnMessage = errorCollection;
					 }
			 }
			 catch (Exception ex)
			 {
                 
                 _logger.LogError(ex,"An exception occurred in - users / Register_Profile, Error Message : " + (ex.StackTrace != null ? $", Stack Trace: {ex.StackTrace.ToString()}" :ex.Message));
               
				 strReturnMessage = ex.Message;
			 }
		     ViewData["message"] = strReturnMessage;
			 if(strReturnMessage.Replace("\"", "").Contains("201.1")){
				 TempData["message"] = "Success";
				 
                 
				return "Success";
			 }else{
				  if(strReturnMessage=="401.1")
				  	 	 strReturnMessage = "Authorization Failed";

				  return strReturnMessage;
			 }
 
		   }

				

Admin/Views/lookups/Create.cshtml
			<!-- This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:16 -->
			@using Microsoft.AspNetCore.Http
@model Marketplacenew.Models.lookupsModel
@{
ViewData["Title"] = "Update  Lookup  Data";
Layout = "~/Views/Shared/_Layout.cshtml";
}

@using(Html.BeginForm("Create", "lookups", FormMethod.Post, new { enctype="multipart/form-data", @id = "formId"}))
{
<div class="" style="margin-left:5px;">
@if(ViewData["message"] != null)
{
<div class="row">
<div class="col-sm-12 col-xs-12">
<div class="alert alert-danger alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">x</span>
</button>
Info :  @ViewData["message"]
</div>
</div>
</div>
}
<div class="card card-container-Padding">
<div class="card-block">
					@Html.HiddenFor(m => m.lookupid)
					@Html.HiddenFor(m => m.attributetype)
					
		<div class="row">
		<div class="col-sm-4 p-2">
			<div>
			   <label>Entity Name</label>
				<div class="form-group" > 
					@Html.TextBoxFor(m => m.entityname, new {@readonly="readonly",@maxlength="256", @class = "form-control form-control-lg required" })
					<i class="form-group__bar" ></i>
					
				</div>
				@Html.ValidationMessageFor(model => model.entityname)
				<label id="entityname-error" class="help-block" style="display: none" for="entityname"></label>
			</div>
		</div>
		<div class="col-sm-4 p-2">
			<div>
			   <label>Field Name</label>
				<div class="form-group" > 
					@Html.TextBoxFor(m => m.fieldname, new {@readonly="readonly",@maxlength="256", @class = "form-control form-control-lg required" })
					<i class="form-group__bar" ></i>
					
				</div>
				@Html.ValidationMessageFor(model => model.fieldname)
				<label id="fieldname-error" class="help-block" style="display: none" for="fieldname"></label>
			</div>
		</div>
		<div class="col-sm-12 col-xs-12 p-2">
			<div>
				<label>Lookup Values</label>
				<div class="form-group" > 
					@Html.TextBoxFor(m => m.fielddesc, new {@type="text",@maxlength="1084", @class = "required" })
					<i class="form-group__bar" ></i>
					
					<label id="fielddesc-error" class="help-block" style="display: block" for="fielddesc"></label>
				</div>
				@Html.ValidationMessageFor(model => model.fielddesc)
				<label id="fielddesc-success" class="help-block" style="display:block" for="fielddesc">Type to Add More Items..</label>
				
			</div>
		</div> 

		</div>
		<div class="card-block">
				<a href= "@Url.Action("Index","lookups")" class="btn btn-secondary waves-effect cma_cancel_button">Cancel</a>
				<button type="submit" id="btnSubmit" class="btn btn-blue  waves-effect pull-right cma_primary_button">Submit</button>
		</div>
</div>
</div>
</div>
}
<script src="~/components/jquery/jquery.validate.js"></script>
<script src="~/components/jquery/additional-methods.min.js"></script>

<link rel="stylesheet" href="~/components/Selectize/dist/css/selectize.default.css">
<script src="~/components/Selectize/dist/js/standalone/selectize.js"></script>
<script src="~/components/Selectize/basic/js/index.js"></script>

<script>
$(document).ready(function () {

  $("#fielddesc").selectize({
                persist: true,
                createOnBlur: true,
                create: true
                });
				
		$('#formId').validate({
		ignore: ':hidden:not([class~=selectized]),:hidden > .selectized, .selectize-control .selectize-input input',
		highlight: function(element) {
		$(element).closest('.form-group').addClass('has-danger');
		$(element).closest('.form-group').removeClass('has-success');
		$(element).addClass('form-control-danger');
		$(element).removeClass('form-control-success');
		},
		unhighlight: function(element) {
		$(element).closest('.form-group').removeClass('has-danger');
		$(element).closest('.form-group').addClass('has-success');
		$(element).addClass('form-control-success');
		$(element).removeClass('form-control-danger');
		},
		errorElement: 'label',
		errorClass: 'help-block'
		});
})
var str = "";
</script>







<script>
$(document).ready(function () {
var validator = $("#formId").validate({ /* settings */ });
$("#btnSubmit").click(function(){
if ($("#formId").valid()){
$(".page-loader").show()
$("#formId").submit();
}else{
validator.focusInvalid();
swal({
title: 'Validation !',
text: "Please fill Empty Fields",
type: 'error',
buttonsStyling: false,
confirmButtonClass: 'btn btn-primary'
 })
}
})
})
$('form:first *:input[type!=hidden]:first').focus();
</script>

Admin/Views/lookups/Index.cshtml
			<!-- This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:16 -->
			@using Microsoft.AspNetCore.Http
@{
ViewData["Title"] = "List of  Lookup  Data";
Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card" style="margin-left:5px;padding:20px;">
<div class="card-body" style="padding:20px;padding-top:0px;">
@if(TempData["message"] != null)
{
<div class="row">
<div class="col-sm-12 col-xs-12">
<div class="alert alert-success alert-dismissible fade show">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">x</span>
</button>
Info :  @TempData["message"]
</div>
</div>
</div>
}
	<div class="row" style="margin-bottom:20px"><div class="col-sm-12 col-xs-12">
	<div class="table-responsive" style="margin:0px;">
		<table id="lookups" class="table order-column hover responsive nowrap" width="100%" style="margin:0px; ">
			 <thead class="thead-default">
				<tr>
				<th>Entity Name</th>
				<th>Field Name</th>
				<th>Lookup Values</th>
				<th class="all">Action</th>

				</tr>
			</thead>
		<tbody></tbody>
			 
		</table>
	</div>

	</div></div>
	</div>
</div>

 
  
	<script type="text/javascript">
	$(document).ready(function () {
 
 
	var table=$("#lookups").DataTable({
	destroy:true,
	"bStateSave": true,
"order": [],
"aaSorting": [],
	autoWidth: !1,
	responsive:!0,
	lengthMenu: [
	[15, 30, 45, -1],
	["15 Rows", "30 Rows", "45 Rows", "Everything"]
	],
	language: {
	searchPlaceholder: "Search for records..."
	},
	 language: { search: '<i class="fa fa-search"></i>', searchPlaceholder: "Search for records..." },
	dom: "Bfrtip",
	   sDom: '<"dataTables__top"lfB>rt<"dataTables__bottom"ip><"clear">',
	buttons: [{
	extend: "excelHtml5",
	title: "List Of Lookup Data"
	}, {
	extend: "csvHtml5",
	title: "List Of Lookup Data"
	}, {
	extend: "print",
	title: "List Of Lookup Data"
	}],
 initComplete: function(a, b) {
      $(this).closest(".dataTables_wrapper").find(".dt-buttons").hide();
       $(this).closest(".dataTables_wrapper").find(".dataTables__top").prepend(`
        <div class="dataTables_buttons hidden-sm-down actions">
          <i class="actions__item mdi material-icons" data-table-action="fullscreen">fullscreen</i>
          <div class="dropdown actions__item">
            <i data-toggle="dropdown" class="material-icons">share</i>
            <ul class="dropdown-menu dropdown-menu-right">
              <a href="javascript: void 0" class="dropdown-item" data-table-action="excel">Excel (.xlsx)</a>
              <a href="javascript: void 0" class="dropdown-item" data-table-action="csv">CSV (.csv)</a>
              <a href="javascript: void 0" class="dropdown-item" data-table-action="print">Print</a>
            </ul>
          </div>`)

 

    },columns: [
{ data: 'entityname' },
{ data: 'fieldname' },
{ data: 'fielddesc' },
{
		"sName": "lookupid",
		"bSearchable": false,
		"bSortable": false,
		data: 'lookupid', "className": "dt-center",
		mRender: function(data, type, row) {
var returnButton="";
				var CreateURL = "@Url.Action("Create", "lookups")?id=" + row["lookupid"]
			 
			 returnButton=returnButton+ '<div class="dropdown actions__item">' +
'<i data-toggle="dropdown" class="fa fa-ellipsis-v"></i>' +
'<div class="dropdown-menu dropdown-menu-right">';
returnButton=returnButton+'<a href="' + CreateURL + '" class="dropdown-item">Change</a>'
 

returnButton=returnButton+'</div></div>'
return returnButton
		}
		}

	 ],
	ajax: {
	url: "@Url.Action("get_lookups", "lookups")",
	type: 'GET',
	dataType: 'json',
	dataSrc: '',
	error: function(jqXHR, textStatus, errorThrown) {
	if (JSON.stringify(jqXHR.responseText) == "\"API Authorization failed\"")
	{
	swal({
	title: 'Failed!',
	text: jqXHR.responseText,
	type: 'error',
	buttonsStyling: false,
	confirmButtonClass: 'btn btn-primary',
	allowOutsideClick: false
	}).then(function() {
	window.location = "@Url.Action("AuthorizationFailed", "users")"
	}) 
	}
	else
	{
		swal({
		title: 'Contact Administrator !',
		text: jqXHR.responseText,
		type: 'error',
		buttonsStyling: false,
		confirmButtonClass: 'btn btn-primary'
		}) 
	}
	}
	}
	})

   $('.ColVis_collection li').on('click', function(event) {
    event.stopPropagation();
  });

  $('.colvis_switch').on('change', function(e) {
    var column = dataTable.column($(this).attr('data-column'));
    column.visible(!column.visible());
  });

  $(".dataTables_filter input[type=search]").focus(function() {
    $(this).closest(".dataTables_filter").addClass("dataTables_filter--toggled")
  }), $(".dataTables_filter input[type=search]").blur(function() {
    $(this).closest(".dataTables_filter").removeClass("dataTables_filter--toggled")
  })

  $("body").on("click", "[data-table-action]", function(a) {
    a.preventDefault();
    var b = $(this).data("table-action");
    console.log('dataTables_wrapper', $(this).closest(".dataTables_wrapper").find(".buttons-print"));
    if ("excel" === b && $(this).closest(".dataTables_wrapper").find(".buttons-excel").trigger("click"), "csv" === b && $(this).closest(".dataTables_wrapper").find(".buttons-csv").trigger("click"), "print" === b && $(this).closest(".dataTables_wrapper").find(".buttons-print").trigger("click"), "fullscreen" === b) {
      var c = $(this).closest(".card");
      c.hasClass("card--fullscreen") ? (c.removeClass("card--fullscreen"), $("body").removeClass("data-table-toggled")) : (c.addClass("card--fullscreen"), $("body").addClass("data-table-toggled"))
    }
  });   
 
});
</script>