Admin/Controllers/MailLogsController.cs
namespace Admin.Controllers
			{
				using System;
				using System.Data;
				using System.Linq;
				using Microsoft.AspNetCore.Mvc;
				using Newtonsoft.Json;
				using System.Net.Http;
				using System.Net.Http.Formatting;
				using System.Threading.Tasks;
				using System.Net.Http.Headers;
				using Microsoft.Extensions.Options;
				using Microsoft.AspNetCore.Http;
				using System.Collections.Generic;
				using System.IO;
				using Microsoft.AspNetCore.Hosting;
				using System.Net;
				using FluentValidation.Results;
				using Marketplacenew.Models;
				using Microsoft.AspNetCore.Mvc.Infrastructure;
				using Microsoft.AspNetCore.HttpOverrides;
                using Microsoft.Extensions.Configuration;
                using Microsoft.Extensions.Logging;
                using System.Threading;
	            using System.Globalization;
                using System.Text.Json;
using Microsoft.AspNetCore.Authorization;

                
                
                
				//This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:25
				
                
                
                
                
				public class MailLogsController : BaseController
				{	 
					private IWebHostEnvironment hostingEnv;
					private IOptions<ApiSettings> _balSettings;
                    private IOptions<MailSettings> _mailSettings;
					private string  url = "";
					private string  baseUrl = "";
                    private string  adminUrl = "";
                    private string  clientUrl = "";
                    private string  accesskey = "";
					private IHttpContextAccessor _accessor;
                    public IConfiguration Configuration { get; }
                    private readonly ILogger<MailLogsController> _logger;
                    
                    
                    
					public MailLogsController(IConfiguration configuration,IHttpContextAccessor accessor,IOptions<ApiSettings> ApiSettings, IOptions<MailSettings> MailSettings, IWebHostEnvironment env, ILogger<MailLogsController> logger):base( configuration)
					{
                        _logger = logger;
						this.hostingEnv = env;
						_balSettings = ApiSettings;
                        _mailSettings = MailSettings;
						url = _balSettings.Value.apiURL;
						baseUrl = _balSettings.Value.baseURL;
                        adminUrl = _balSettings.Value.adminURL;
                        clientUrl = _balSettings.Value.clientURL;
                        accesskey = _balSettings.Value.accesskey;
 
						_accessor = accessor;
                        Configuration = configuration;
                        
					}
						 
 
                public virtual IActionResult detail()
                {
                    return View();
                }
                     public virtual IActionResult audit()
			         {
					        return View();
			         }
	

					
			  public virtual IActionResult Create_MailLog()
			  {
					return View();
			  }	
			  [HttpPost()]
			public virtual async Task<string> Create_MailLog(MailLogsModel model, IFormCollection collection)
			{
				string strReturnMessage = "";
				
				try
				{
					ModelState.Remove("MailLogsid");
					ModelState.Remove("createduser");
                    ModelState.Remove("craftmyapp_actionmethodname");
                    model.craftmyapp_actionmethodname="Create_MailLog";
					if(HttpContext.Session.GetString("MarketplacenewloginUserID") != null)
								model.createduser =new Guid(HttpContext.Session.GetString("MarketplacenewloginUserID"));
								else
								return "Session Expired";
					
					
			 	 
					 if (ModelState.IsValid)
					 {
							 MailLogsModelValidator validator = new MailLogsModelValidator();
							 ValidationResult results = validator.Validate(model);
							 if (!results.IsValid)
							 {
								 var errorCollection = string.Join(" | ", results.Errors.Select(e => e.ErrorMessage.Replace("{propertyName}",e.PropertyName)));
								 strReturnMessage = errorCollection.ToString();
								 foreach (var failure in results.Errors)
								 {
									ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
								 }
							 }
							 else
							 {
								 model.MailLogsid =Guid.NewGuid();
								 
                                 strReturnMessage = await ApiClient.Post_ApiValuesGetString(getHttpClient(),"api/MailLogs/Create_MailLog", model);
                                    
								 
							 }
					 }
					 else
					 {
							   var errorMessages = ModelState.Where(entry => entry.Value.Errors.Any()).SelectMany(entry => entry.Value.Errors.Select(error => $"{entry.Key}: {error.ErrorMessage}"));
                               var errorCollection = string.Join(" | ", errorMessages);
                               strReturnMessage = errorCollection;
					 }
			 }
			 catch (Exception ex)
			 {
                 
                 _logger.LogError(ex,"An exception occurred in - MailLogs / Create_MailLog, Error Message : " + (ex.StackTrace != null ? $", Stack Trace: {ex.StackTrace.ToString()}" :ex.Message));
               
				 strReturnMessage = ex.Message;
			 }
		     ViewData["message"] = strReturnMessage;
			 if(strReturnMessage.Replace("\"", "").Contains("201.1")){
				 TempData["message"] = "Success";
				 
                 
				return "Success";
			 }else{
				  if(strReturnMessage=="401.1")
				  	 	 strReturnMessage = "Authorization Failed";

				  return strReturnMessage;
			 }
 
		   }

				
			  public virtual async Task<IActionResult> Update_MailLog(string MailLogsid)
			  {

                    string redirectTo="";
                    if(HttpContext.Session.GetString("Marketplacenewrole_JSON") != null){
                            DataTable Marketplacenewrole_JSON =HttpContext.Session.GetSession<DataTable>("Marketplacenewroles");
                            DataView dv = new DataView(Marketplacenewrole_JSON);
                            dv.RowFilter = "controllername='MailLogs' AND viewname='list'";

                            if(dv.Count  >0){
                                redirectTo = dv[0]["actionmethodname"] as string;
							 
                            }

                            try{
                                     var jsonObjMailLogs = await ApiClient.Get_ApiValues(getHttpClient(), "api/MailLogs/getById_MailLogs?MailLogsid="+MailLogsid+"&loginUserID="+HttpContext.Session.GetString("MarketplacenewloginUserID"));
                                if(jsonObjMailLogs.Length > 2)
                                {
                                  
                                    var model = JsonConvert.DeserializeObject<MailLogsModel>(jsonObjMailLogs);


                
                                     
                                    return View("Create_MailLog", model);
                                }
                                else
                                {
                    
                                    TempData["message"] = "Data Not Found - Contact Administrator";
                                    return RedirectToAction(redirectTo);
						 
                                }

                            }catch(Exception ex){
                               _logger.LogError(ex,"An exception occurred in - MailLogs / Update_MailLog, Error Message : " + (ex.StackTrace != null ? $", Stack Trace: {ex.StackTrace.ToString()}" :ex.Message));
              
                                TempData["errMessage"] = "Error while fetching data - Contact Administrator";
                                return RedirectToAction(redirectTo);
                            }

                    }
                    TempData["errMessage"] = "Session Expired";
                    return RedirectToAction("Logout", "users");
                }	
			  [HttpPost()]
				public virtual async Task<string> Update_MailLog(MailLogsModel model, IFormCollection collection)
				{
					string strReturnMessage = "";
					try
					{
							ModelState.Remove("MailLogsid");
                            ModelState.Remove("craftmyapp_actionmethodname");
                             model.craftmyapp_actionmethodname="Update_MailLog";
							
							
							if(HttpContext.Session.GetString("MarketplacenewloginUserID") != null)
					model.modifieduser =new Guid(HttpContext.Session.GetString("MarketplacenewloginUserID"));
					else
					return "Session Expired";
							

                            
							if (ModelState.IsValid)
							{
									MailLogsModelValidator validator = new MailLogsModelValidator();
									ValidationResult results = validator.Validate(model);
									if (!results.IsValid)
									{
										var errorCollection = string.Join(" | ", results.Errors.Select(e => e.ErrorMessage.Replace("{propertyName}",e.PropertyName)));
										strReturnMessage = errorCollection.ToString();
										foreach (var failure in results.Errors)
										{
											ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
										}
									}
									else
									{
                                        
										
                                        
                                        
                                        strReturnMessage = await ApiClient.Post_ApiValuesGetString(getHttpClient(),"api/MailLogs/Update_MailLog", model);
 									}
							}
							else
							{
									var errorMessages = ModelState.Where(entry => entry.Value.Errors.Any()).SelectMany(entry => entry.Value.Errors.Select(error => $"{entry.Key}: {error.ErrorMessage}"));
                               var errorCollection = string.Join(" | ", errorMessages);
                               strReturnMessage = errorCollection;
							}
					}
					catch (Exception ex)
					{

Admin/Views/MailLogs/Create_MailLog.cshtml
			<!-- This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:26 -->
			@using Microsoft.AspNetCore.Http
			@inject IHttpContextAccessor HttpContextAccessor
            @using Admin;
			@model Marketplacenew.Models.MailLogsModel
			@{
			ViewData["Title"] = @Resource.createmaillog;

			Layout = "~/Views/Shared/_Layout.cshtml";
			
			}

			@using(Html.BeginForm("Create_MailLog", "MailLogs", FormMethod.Post, new { enctype="multipart/form-data", @id = "formId"}))
			{

			<div class="card card-block contCard"><!--Form_Main_Card-->
				<div class="mobileHeader"><!--form_card_header-->
					<div class="row">
						<div class="col-sm-12 col-xs-12">
							<h4 class="formHdr">@Resource.createmaillog</h4>
						</div>
					</div>
				</div><!--form_card_header-->
				<!--form_error_display-->
				@if(ViewData["message"] != null)
				{
				<div class="row">
				<div class="col-sm-12 col-xs-12">
				<div class="alert alert-danger alert-dismissible ">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">x</span>
				</button>
				Info :  @ViewData["message"]
				</div>
				</div>
				</div>
				}
				
				
				 
				
				<!--form_error_display-->
				<div class=""><!--form_inner_card-->
					<div class="card-block"><!--form_inner_card_block-->
					    @Html.HiddenFor(m => m.MailLogsid)
                            
						 

						
						<div class="row"><!--field_container_row-->
							<!--fieldsStartsHere-->
						       		
								<div class="col-sm-3 col-xs-12 p-2 entityname_craftmyapp_container">
						<div>
							<div class="form-group" > 
								<label for="entityname">@Resource.maillogs_entityname <b class="iconRed">*</b></label>
                                @Html.TextBoxFor(m => m.entityname, new {@type="text",@maxlength="128", @class = "form-control form-control-lg mahat_transliterate required" })

							     @Html.ValidationMessageFor(model => model.entityname)
							</div>
						</div>
					</div>
<div class="col-sm-3 col-xs-12 p-2 entityid_craftmyapp_container">
						<div>
							<div class="form-group" > 
								<label for="entityid">@Resource.maillogs_entityid</label>
                                @Html.TextBoxFor(m => m.entityid, new {@type="text",@maxlength="128", @class = "form-control form-control-lg mahat_transliterate " })

							     @Html.ValidationMessageFor(model => model.entityid)
							</div>
						</div>
					</div>
<div class="col-sm-3 col-xs-12 p-2 mailfor_craftmyapp_container">
						<div>
							<div class="form-group" > 
								<label for="mailfor">@Resource.maillogs_mailfor</label>
                                @Html.TextBoxFor(m => m.mailfor, new {@type="text",@maxlength="256", @class = "form-control form-control-lg mahat_transliterate " })

							     @Html.ValidationMessageFor(model => model.mailfor)
							</div>
						</div>
					</div>
<div class="col-sm-3 col-xs-12 p-2 mailsubject_craftmyapp_container">
						<div>
							<div class="form-group" > 
								<label for="mailsubject">@Resource.maillogs_mailsubject</label>
                                @Html.TextBoxFor(m => m.mailsubject, new {@type="text",@maxlength="256", @class = "form-control form-control-lg mahat_transliterate " })

							     @Html.ValidationMessageFor(model => model.mailsubject)
							</div>
						</div>
					</div>
<div class="col-sm-3 col-xs-12 p-2 mailto_craftmyapp_container">
						<div>
							<div class="form-group" > 
								<label for="mailto">@Resource.maillogs_mailto</label>
                                @Html.TextBoxFor(m => m.mailto, new {@type="text",@maxlength="4096", @class = "form-control form-control-lg mahat_transliterate " })

							     @Html.ValidationMessageFor(model => model.mailto)
							</div>
						</div>
					</div>
<div class="col-sm-12 col-xs-12 p-2 mailbody_craftmyapp_container">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="mailbody">@Resource.maillogs_mailbody</label>
															@Html.TextAreaFor(m => m.mailbody, new {@class = "form-control mahat_transliterate wysiwyg-editor " })

										<i class="form-group__bar" ></i>
									</div>
									@Html.ValidationMessageFor(model => model.mailbody)
									<div id="mailbody-error" class="help-block" style="display: none" role="alert"></div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-4 issent_craftmyapp_container">
							<div>

							<label for="issent">@Resource.maillogs_issent</label><br>
							<div class="form-group">
                                                        <div>
                                                          <label class="switch" for="issent">
                                                          @Html.CheckBoxFor(m => m.issent,new {@class = "" })
                                                           
                                                          <span class="slider round"></span>
                                                        </label>
                                                        </div>
                                                      </div>

							</div>
							</div>


							<!--fieldsEndsHere-->	
						</div><!--field_container_row-->


						<div class="card-block"><!--form_button_card_block-->
							<button type="button" onclick="window.history.back()"  class="btn btn-secondary cma_cancel_button waves-effect">@Resource.back</button>
							<button type="button" id="btnSubmit" class="btn cma_primary_button  cma_save_button waves-effect pull-right">@Resource.createmaillog</button>
						</div><!--form_button_card_block-->


					</div><!--form_inner_card_block-->
				</div><!--form_inner_card-->
			</div><!--Form_Main_Card-->

			}<!--EndFORM-->


			
			 <!--from_cma_script-->
			 <script type="text/javascript">
				$(document).ready(function () {


				var Actions=getAutho("MailLogs","create")
				if(Actions == undefined){
				window.location = "@Url.Action("RoleAuthorizationFailed", "users")"
				}


				});
				</script>
			
			<link href="~/components/trumbowyg/dist/ui/trumbowyg.css" rel="stylesheet" />
<script src="~/components/trumbowyg/dist/trumbowyg.js"></script>
<script>$('#mailbody').trumbowyg();</script>

			
			
			
			
			<script>
            
			
			
			</script>
			
  
 
                            <script>
                            var posturl='';
                            </script>

                             @if (Model == null)
                             {
	                             <script>
                                posturl = '@Url.Action("Create_MailLog")';
	                            </script>
                            }else{
	   
	                                <script>
                                                   posturl = '@Url.Action("Update_MailLog")';
			 
						                                  </script>    			              
                              
	 
							                            ViewData["Title"] = @Resource.updatemaillog;
						                                 <script>
                   
					                                 $("#btnSubmit").html("@Resource.updatemaillog")
						                                  </script>    
 
 
                            }

<script>
$(document).ready(function () {
	
	
           
                $.validator.addMethod("invalidphone", function (value, element) {
                if (value == 'invalid') {
                return false;
                }
                return true;
                }, "Please enter valid value");

                                        $('#formId').validate({
                                        ignore: ":hidden:not(.invalidphone)",
                                        highlight: function(element) {
                                        $(element).closest('.form-group').addClass('has-error');
                                        $(element).closest('.form-group').removeClass('has-success');
                                        $(element).addClass('form-control-error');
                                        $(element).removeClass('form-control-success');
                                        },
                                        unhighlight: function(element) {
                                        $(element).closest('.form-group').removeClass('has-error');
                                        $(element).closest('.form-group').addClass('has-success');
                                        $(element).addClass('form-control-success');
                                        $(element).removeClass('form-control-error');
                                        },
                                        errorElement: 'span',
                                        errorClass: 'help-block',
                                        errorPlacement: function (error, element) {
                                                    if (element.hasClass("invalidphone")) {
                                                        error.addClass("invalidphoneerror");
                                                        error.insertAfter(element);
                                                    } else {
                                                        error.insertAfter(element);
                                                    }
                                                }
                                        });
 	 
var validator = $("#formId").validate({ /* settings */ });
 
$("#btnSubmit").click(function(){
 
 
 

 
 

if ($("#formId").valid()){
 $(".page-loader").show()
 
 var form = $('#formId')[0];
 var formdata = new FormData(form);

 

 
 
 
 

 
$.ajax({
url: posturl,
type:'POST',
enctype: 'multipart/form-data',
processData: false,   
contentType: false,
cache: false,
data: formdata,
success: function(data) {
  
  $(".page-loader").hide();
 if(data=="Success"){
 $(".page-loader").hide();

 	var Actions_=getAutho("MailLogs","list")
	if(Actions_ !=  undefined)
	{
		var list_URL = "@Url.Action("entry.viewname", "MailLogs")"
		                                                                list_URL = list_URL.replace("entry.viewname", Actions_.actionmethodname);
		                                                                window.location=list_URL;
	 
	}
   
 }
    else {
                                $(".page-loader").hide();
                                swal({
                                    title: "Error !!",
                                    text: data,

                                    type: "error",
                                    showCancelButton: false,
                                    confirmButtonText: "OK",
                                })


                            }

 
},
	error: function(jqXHR, textStatus, errorThrown) {
	if (JSON.stringify(jqXHR.responseText) == "\"API Authorization failed\"")
	{
	swal({
	title: 'Failed!',
	text: jqXHR.responseText,
	type: 'error',
	buttonsStyling: false,
	confirmButtonClass: 'btn btn-primary',
	allowOutsideClick: false
	}).then(function() {
	window.location = "@Url.Action("AuthorizationFailed", "users")"
	}) 
	}
	else
	{
	swal({
	title: 'Contact Administrator !',
	text: jqXHR.responseText,
	type: 'error',
	buttonsStyling: false,
	confirmButtonClass: 'btn btn-primary'
	}) 
	}
	}
})




}else{
validator.focusInvalid();
swal({
title: 'Validation Failed !',
text: "Please check your entry",
type: 'error',
buttonsStyling: false,
confirmButtonClass: 'btn btn-primary'
 })
}
})
})


</script>

			
			
            
            

			 
             
                


			 <!--to_cma_script-->
			

Admin/Views/MailLogs/detail.cshtml
					<!--This code generated from staging Powered by Mahat, Source Machine : stg , Build Number : #2024-07-004 (Updated on 07/07/2024 22:07) on 05/06/2025 11:28:26 -->
					@using Microsoft.AspNetCore.Http
					@inject IHttpContextAccessor HttpContextAccessor
                    @using Admin;
					@model Marketplacenew.Models.MailLogsModel
					@{
					ViewData["Title"] = "MailLogs";
					Layout = "~/Views/Shared/_Layout.cshtml";
					}

					<div class="">
					     
					<div class="">

					      <div id="cma_printableArea">
                           
                            
                            <div class="row printablerow"  style="padding:20px"> 
                              <div class="col-sm-12 col-xs-12 p-1 entityname_craftmyapp_viewcontainer show-on-pdf" style="display:none;text-align:left">
                            <h3>
                            <img src="~/images/logo.png" style="height:60px;width:60px;" alt="logo">
                            <b>MailLogs</b>
                            </h3>
				
                            <br />
                            </div>
                            <div class="col-sm-3 col-xs-12 p-2 entityname_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="entityname">@Resource.maillogs_entityname</label><br>
										<span class="auto_cls_entityname"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-2 entityid_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="entityid">@Resource.maillogs_entityid</label><br>
										<span class="auto_cls_entityid"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-2 mailfor_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="mailfor">@Resource.maillogs_mailfor</label><br>
										<span class="auto_cls_mailfor"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-2 mailsubject_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="mailsubject">@Resource.maillogs_mailsubject</label><br>
										<span class="auto_cls_mailsubject"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-2 mailto_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="mailto">@Resource.maillogs_mailto</label><br>
										<span class="auto_cls_mailto"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-2 mailbody_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="mailbody">@Resource.maillogs_mailbody</label><br>
										<span class="auto_cls_mailbody"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>
<div class="col-sm-3 col-xs-12 p-2 issent_craftmyapp_viewcontainer">
								<div>
									<div class="form-group form-group--float-above my-3" > 
										<label for="issent">@Resource.maillogs_issent</label><br>
										<span class="auto_cls_issent"></span>
										<i class="form-group__bar" ></i>
									</div>
								</div>
							</div>

											 
											 
                            </div>
                         </div>
						 <div class="row">
					            <div class="col-sm-12 col-xs-12">
					           
                                 <button type="button" onclick="window.history.back()" class="btn btn-secondary cma_cancel_button cma_back_button waves-effect">@Resource.back</button>            

					            </div>
					        </div>					
  
                    </div>
					
                    <link href="~/components/jquery-colorbox/colorbox.css" rel="stylesheet" />
                    <script src="~/components/jquery-colorbox/jquery.colorbox.js"></script>
                    <link href="~/css/GallaryContent/style.css" rel="stylesheet" />
                    <link href="~/components/starrr/starrr.css" rel="stylesheet" />
					 
					 <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>
					<script type="text/javascript">
                     function download() {
                            const element = document.getElementById('cma_printableArea');

                            const elementsToHide = document.querySelectorAll('.show-on-pdf');

                            // Hide the elements
                            elementsToHide.forEach(function (el) {
                            el.style.display = '';
                            });

                            html2pdf()
                            .from(element)
                            .save('MailLogs.pdf')
                            .then(function () {
                            // Show the hidden elements after generating PDF
                            elementsToHide.forEach(function (el) {
                            el.style.display = 'none';
                            });
                            });
                    }
                    function fill_MailLogs_view_data(){

                       var  MailLogsid = getUrlVars()["id"];
                                            $("#viewDetails_Auto").show()
											$(".auto_checker_action").hide()
                                                $.ajax({
												url: '@Url.Action("getById_allinfo_MailLogs")',
												dataType: 'json',
												data:{MailLogsid: MailLogsid },
												success: function(data) {

												var obj=eval(data[0]);
													for (var key in obj) {
													
                                                            
															$(".auto_cls_"+key).html(obj[key]|| '-');
														 	
															

                                                            

													}

                                                    
												}

												})

                   }
                   

					$(document).ready(function () {


					fill_MailLogs_view_data()


					/*var Actions=getAutho("MailLogs","list")
					if(Actions == undefined){
					window.location = "@Url.Action("RoleAuthorizationFailed", "users")"
					}*/




					});
					 
					</script>
					 
                    
                    <script type="text/javascript">
                        
                        $(document).ready(function () {
                            
                        });
                    </script>
                    
                    
					